# Generated by Django 5.0.7 on 2024-07-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_path', models.CharField(blank=True, max_length=100, null=True)),
                ('path', models.CharField(max_length=100)),
                ('path_variables', models.CharField(blank=True, max_length=100, null=True)),
                ('method', models.CharField(max_length=10)),
                ('tags', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('operation_id', models.CharField(blank=True, max_length=255)),
                ('requestBody', models.TextField(blank=True, null=True)),
                ('parameters', models.TextField(blank=True, null=True)),
                ('responses', models.TextField(blank=True)),
                ('authentication', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HarFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.FileField(upload_to='har_file/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
