# Generated by Django 5.0.7 on 2024-07-15 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dependency_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoints',
            name='description',
        ),
        migrations.RemoveField(
            model_name='endpoints',
            name='operation_id',
        ),
        migrations.RemoveField(
            model_name='endpoints',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='endpoints',
            name='tags',
        ),
    ]
