# Generated by Django 5.0.7 on 2024-07-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependency_app', '0004_rename_path_variables_endpoints_query_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoints',
            name='response_header',
            field=models.TextField(blank=True),
        ),
    ]
