# Generated by Django 5.0.7 on 2024-07-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependency_app', '0005_endpoints_response_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoints',
            name='responsebody',
            field=models.TextField(blank=True),
        ),
    ]
