# Generated by Django 5.0.7 on 2024-07-15 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dependency_app', '0006_endpoints_responsebody'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endpoints',
            old_name='parameters',
            new_name='headers',
        ),
    ]
