# Generated by Django 5.0.7 on 2024-07-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependency_app', '0008_endpoints_authentication'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoints',
            name='dependencies',
            field=models.ManyToManyField(blank=True, to='dependency_app.endpoints'),
        ),
    ]
