# Generated by Django 5.0.7 on 2024-07-15 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dependency_app', '0009_endpoints_dependencies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoints',
            name='dependencies',
        ),
    ]
