# Generated by Django 5.0.7 on 2024-07-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependency_app', '0011_endpoints_referrer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endpoints',
            old_name='referrer',
            new_name='request_parameters',
        ),
        migrations.AddField(
            model_name='endpoints',
            name='resonse_parameters',
            field=models.TextField(blank=True),
        ),
    ]
