# Generated by Django 5.0.7 on 2024-07-16 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dependency_app', '0013_rename_resonse_parameters_endpoints_response_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoints',
            name='request_parameters',
        ),
        migrations.RemoveField(
            model_name='endpoints',
            name='response_parameters',
        ),
    ]
