# Generated by Django 5.0.7 on 2024-07-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependency_app', '0016_endpoints_referrer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoints',
            name='request_parameters',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='endpoints',
            name='response_parameters',
            field=models.JSONField(blank=True),
        ),
    ]
