# Generated by Django 5.0.7 on 2024-07-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependency_app', '0017_alter_endpoints_request_parameters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoints',
            name='request_parameters',
            field=models.JSONField(max_length=500),
        ),
        migrations.AlterField(
            model_name='endpoints',
            name='response_parameters',
            field=models.JSONField(max_length=500),
        ),
    ]
