# Generated by Django 5.0.7 on 2024-07-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependency_app', '0021_alter_endpoints_request_parameters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoints',
            name='dependency_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
