# Generated by Django 5.0.7 on 2024-08-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependency_app', '0022_endpoints_dependency_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoints',
            name='is_producer_api',
            field=models.BooleanField(default=False),
        ),
    ]
