# Generated by Django 5.0.7 on 2024-08-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependency_app', '0023_endpoints_is_producer_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoints',
            name='login_endpoint',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
