# Generated by Django 5.0.7 on 2024-08-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependency_app', '0024_endpoints_login_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoints',
            name='start_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
