# Generated by Django 5.0.7 on 2024-08-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependency_app', '0025_endpoints_start_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoints',
            name='dependency_list_sorted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
