# Generated by Django 5.0.7 on 2024-08-22 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dependency_app', '0026_endpoints_dependency_list_sorted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoints',
            name='dependency_list_sorted',
        ),
    ]
