# Generated by Django 5.0.7 on 2024-08-23 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dependency_app', '0027_remove_endpoints_dependency_list_sorted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoints',
            name='start_date_time',
        ),
    ]
